name: Build and Release PDF

on:
  release:
    types: [published]
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: ./pdf_output
          images_dir: ./images
          image_import: ./images
          build_html: false
      
      - name: Upload PDFs to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./pdf_output/*.pdf
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
